# Generated by Django 4.2 on 2024-11-29 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('food_cost', models.PositiveIntegerField(default=0)),
                ('water_cost', models.PositiveIntegerField(default=0)),
                ('money_cost', models.PositiveIntegerField(default=0)),
                ('wood_cost', models.PositiveIntegerField(default=0)),
                ('stone_cost', models.PositiveIntegerField(default=0)),
                ('effect', models.TextField(help_text='Descripción del efecto del edificio')),
            ],
        ),
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('food', models.PositiveIntegerField(default=0)),
                ('water', models.PositiveIntegerField(default=0)),
                ('money', models.PositiveIntegerField(default=0)),
                ('wood', models.PositiveIntegerField(default=0)),
                ('stone', models.PositiveIntegerField(default=0)),
                ('turn', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('required_turn', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='NationTechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='core.nation')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.technology')),
            ],
        ),
        migrations.CreateModel(
            name='NationBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.building')),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='core.nation')),
            ],
        ),
    ]
